### ISSUE TITLE
Hide sky below terrain

### ISSUE THREAD

**Issue by clabe45** [prophets-of-tron/into-the-woods#22]
Because there is a base starting height at the bottom of terrain, if the player enters a valley, the background sky becomes visible. Possible solutions:

- **Lower terrain base** - will effect performance
- **Add "skybox" with top half (above terrain base) sky color and the bottom half dirt color** - only works with solid color tiles

**Comment by serk12** [comment]
This is a good seed for debugging 

> 1514603668
